// let EventsData = [
//   {
//     id: 1,
//     start: '15:00',
//     end: '16:00',
//     title: 'Hillegom',
//     klant: 'Lissete van deursen',
//     boxen: '1x 8kuub, 2x 14kuub',
//     boxnmr: 'A180, 24, 25',
//   },
//   {
//     id: 23321,
//     start: '12:00',
//     end: '15:00',
//     title: 'Lisse',
//     klant: 'Martijn',
//     boxen: '1x 8kuub',
//     boxnmr: 'A123',
//   },
//   {
//     id: 12354,
//     start: '12:00',
//     end: '15:00',
//     title: 'Lisse',
//     klant: 'Pepijn',
//     boxen: '5x 8kuub',
//     boxnmr: 'A123',
//   },
//   {
//     id: 1024,
//     start: '12:00',
//     end: '15:00',
//     title: 'De zilk',
//     klant: 'Jeroen',
//     boxen: '1x 14kuub',
//     boxnmr: 'A123',
//   },
// ];
